server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: file-store
          uri: http://localhost:8081
          predicates:
            - Path=/files/**

        - id: file-analysis
          uri: http://localhost:8082
          predicates:
            - Path=/analysis/**
